export const API_REQUEST = {
  SUCCESS: "SUCCESS",
  FETCH: "fetch",
  ERROR: "ERROR",
};

export const WISHLIST_API = {
  SUCCESS: "WISHLIST_SUCCESS",
  FETCH: "WISHLIST_FETCH",
  ERROR: "WISHLIST_ERROR",
  DELETE: "WISHLIST_DELETE",
};


export const CART_API = {
  SUCCESS: "CART_SUCCESS",
  FETCH: "CART_FETCH",
  ERROR: "CART_ERROR",
  DELETE: "CART_DELETE",
};
